monsieurbiz_sylius_media_manager_admin_browser_list:
    path: browser/list
    methods: [GET]
    defaults:
        _controller: 'MonsieurBiz\SyliusMediaManagerPlugin\Controller\BrowserController::listAction'
    condition: 'request.headers.get("X-Requested-With") == "XMLHttpRequest"'

monsieurbiz_sylius_media_manager_admin_browser_choose:
    path: browser/choose
    methods: [GET]
    defaults:
        _controller: 'MonsieurBiz\SyliusMediaManagerPlugin\Controller\BrowserController::chooseAction'
    condition: 'request.headers.get("X-Requested-With") == "XMLHttpRequest"'

monsieurbiz_sylius_media_manager_admin_browser_upload:
    path: browser/upload
    methods: [POST]
    defaults:
        _controller: 'MonsieurBiz\SyliusMediaManagerPlugin\Controller\BrowserController::uploadAction'
    condition: 'request.headers.get("X-Requested-With") == "XMLHttpRequest"'

monsieurbiz_sylius_media_manager_admin_browser_create_folder:
    path: browser/folder
    methods: [POST]
    defaults:
        _controller: 'MonsieurBiz\SyliusMediaManagerPlugin\Controller\BrowserController::createFolderAction'
    condition: 'request.headers.get("X-Requested-With") == "XMLHttpRequest"'

monsieurbiz_sylius_media_manager_admin_browser_delete_folder:
    path: browser/deleteFolder
    methods: [POST]
    defaults:
        _controller: 'MonsieurBiz\SyliusMediaManagerPlugin\Controller\BrowserController::deleteFolderAction'
    condition: 'request.headers.get("X-Requested-With") == "XMLHttpRequest"'


monsieurbiz_sylius_media_manager_admin_browser_delete_file:
    path: browser/deleteFile
    methods: [POST]
    defaults:
        _controller: 'MonsieurBiz\SyliusMediaManagerPlugin\Controller\BrowserController::deleteFileAction'
    condition: 'request.headers.get("X-Requested-With") == "XMLHttpRequest"'

monsieurbiz_sylius_media_manager_admin_browser_rename_folder:
    path: browser/renameFolder
    methods: [ POST ]
    defaults:
        _controller: 'MonsieurBiz\SyliusMediaManagerPlugin\Controller\BrowserController::renameFolderAction'
    condition: 'request.headers.get("X-Requested-With") == "XMLHttpRequest"'
